include: package:very_good_analysis/analysis_options.2.4.0.yaml
# include: package:lint/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false


analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore


  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart,lib/**.config.dart,lib/**.gr.dart]

    

